# Font configuration
font:
  size: 14
  normal:
    family: 'DankMono Nerd Font Mono'
    style: Regular

cursor:
  style:
    shape: Beam
  vi_mode_style:
    shape: Block

# Colors (snooker)
colors:
  primary:
    background: '#0f111b'  # background from spaceduck
    foreground: '#adad9b'

  selection:
    background: '#2b302b'
    foreground: '#e5e5d2'

  cursor:
    cursor: '#cdc08b'
    text: '#0f111b'

  normal:
    black: '#2b302b'
    red: '#e52e1a'
    green: '#1c9c20'
    yellow: '#a57230'
    blue: '#0094cf'
    magenta: '#5e72d5'
    cyan: '#1dae87'
    white: '#cdc08b'

  bright:
    black: '#6a6a5b'
    red: '#e5941a'
    green: '#25c528'
    yellow: '#c89b13'
    blue: '#00a3cc'
    magenta: '#df7376'
    cyan: '#5ccc96'
    white: '#e5e5d2'

# Key bindings
key_bindings:
  - { key: F,         mods: Command,        chars: "\x1bf" }
  - { key: B,         mods: Command,        chars: "\x1bb" }
  - { key: D,         mods: Command,        chars: "\x1bd" }
  - { key: H,         mods: Option,         chars: "\x1bh" }
  - { key: J,         mods: Option,         chars: "\x1bj" }
  - { key: K,         mods: Option,         chars: "\x1bk" }
  - { key: L,         mods: Command,        chars: "\x1bl" }
  - { key: S,         mods: Command,        chars: "\x1bs" }
  - { key: T,         mods: Command,        chars: "\x1bt" }
  - { key: O,         mods: Command,        chars: "\x1bo" }
  - { key: O,         mods: Command|Shift,  chars: "\x1bO" }
  - { key: LBracket,  mods: Command,        chars: "\x1b[" }
  - { key: RBracket,  mods: Command,        chars: "\x1b]" }
  - { key: LBracket,  mods: Command|Shift,  chars: "\x1b{" }
  - { key: RBracket,  mods: Command|Shift,  chars: "\x1b}" }
  - { key: Key1,      mods: Command,        chars: "\x1b1" }
  - { key: Key2,      mods: Command,        chars: "\x1b2" }
  - { key: Key3,      mods: Command,        chars: "\x1b3" }
  - { key: Key4,      mods: Command,        chars: "\x1b4" }
  - { key: Key5,      mods: Command,        chars: "\x1b5" }
  - { key: Key6,      mods: Command,        chars: "\x1b6" }
  - { key: Key7,      mods: Command,        chars: "\x1b7" }
  - { key: Key8,      mods: Command,        chars: "\x1b8" }
  - { key: Key9,      mods: Command,        chars: "\x1b9" }
  - { key: Q,         mods: Control,        chars: "\x11"  }
  - { key: Key6,      mods: Control,        chars: "\x1e"  }
