#!/bin/bash

# Gabe Nespoli (gabenespoli@gmail.com)
# mostly adapted from junegunn/dotfiles/install

# set dotfiles and backup dirs {{{1
cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1
BASE=$(pwd)
mkdir -pv bak

# link rc files {{{1
for rc in *rc *profile tmux.conf; do
  [ -e ~/."$rc" ] && mv -v ~/."$rc" bak/."$rc"
  ln -sfv "$BASE/$rc" ~/."$rc"
done

# install apps (homebrew/apt-get) {{{1
if [ "$(uname -s)" = 'Darwin' ]; then
  # Mac Homebrew
  [ -z "$(which brew)" ] &&
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  echo "Updating homebrew"
  brew cask install iterm2 spectacle

  brew install \
    bash readline tmux neovim ranger git tig ctags \
    reattach-to-user-namespace wget hugo \
    pyenv pyenv-virtualenv \
    pandoc pandoc-citeproc pandoc-crossref

  # TODO: set .macos defaults

  # TODO: setup terminfo with italics (should this be moved out of mac-only?

else
  # Ubuntu apt-get
  sudo apt-get install \
    bash readline tmux neovim ranger git tig ctags \
    pandoc pandoc-citeproc pandoc-crossref

  rm -f ~/.tmux.conf
  grep -v reattach-to-user-namespace tmux.conf > ~/.tmux.conf
fi

# git {{{1
if [ ! -e ~/.git-prompt.sh ]; then
  curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.git-prompt.sh
fi
git config --global user.email "gabenespoli@gmail.com"
git config --global user.name "Gabe Nespoli"

# tmux {{{1
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
tmux source-file ~/.tmux.conf

# pyenv {{{1
if hash pyenv >/dev/null; then
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"

  # install neovim python virtualenvs
  # https://github.com/deoplete-plugins/deoplete-jedi/wiki/Setting-up-Python-for-Neovim#using-virtual-environments
  pyenv install 2.7.15
  pyenv install 3.6.7
  pyenv virtualenv 2.7.15 neovim2
  pyenv virtualenv 3.6.7 neovim3
  pyenv activate neovim2
  pip install neovim
  pyenv activate neovim3
  pip install neovim
  pyenv deactivate
fi

# n/vim {{{1
[ -e ~/.vim ] && mv -v ~/.vim bak/vim
mkdir -pv ~/.vim/autoload
curl -fLo ~/.vim/autoload/plug.vim \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

for folder in ftdetect ftplugin spell syntax; do
  ln -sfv "$BASE/vim/$folder" ~/.vim/"$folder"
done

# nvim
mkdir -pv ~/.config/nvim/autoload
ln -sf $BASE/vimrc ~/.config/nvim/init.vim
ln -sf ~/.vim/autoload/plug.vim ~/.config/nvim/autoload/

nvim +PlugInstall +qall

# anaconda {{{1
pyenv install miniconda3-4.3.30
pyenv shell miniconda3-4.3.30
conda install -y scipy numpy pandas matplotlib seaborn bokeh ipython jupyter \
  scikit-learn tensorflow keras
pyenv shell --unset
mkdir -pv ~/.ipython/profile_default
ln -sfv "$BASE"/ipython/profile_default/ipython_config.py \
  ~/.ipython/profile_default/ipython_config.py
