# example theme.yml: https://github.com/eza-community/eza/blob/main/docs/theme.yml
# list of default icons: https://github.com/eza-community/eza/blob/main/src/output/icons.rs

filenames:
  vimrc: {icon: {glyph:  }}
  ghostty: {icon: {glyph: 󰊠 }}
  todo.txt: {icon: {glyph:  }}
  .gitconfig: {icon: {glyph:  }}
  .gitconfig_local: {icon: {glyph:  }}
  .gitattributes: {icon: {glyph:  }}
  .gitignore: {icon: {glyph:  }}
  gitconfig: {icon: {glyph:  }}
  gitignore: {icon: {glyph:  }}
extensions:
  saql: {icon: {glyph:  }}
