#!/bin/bash

# pandoc md to docx with references
# USAGE: pandoc_md2docx_refs input.md output_with_refs.docx

# filename=$(basename -s .md $1)".docx"

tmpfile="tmp_"$1
cp "$1" "$tmpfile"

pandoc \
-f markdown $tmpfile \
-t latex -o $2 \
--standalone \
--smart \
--toc \
--variable lof=true \
--filter pandoc-citeproc \
--bibliography=$HOME/bin/cite/library.bib \
--csl=$HOME/bin/pandoc/apa-no-doi-no-issue.csl \
#--template=$HOME/bin/pandoc/md2latex/apa6template.tex \

rm $tmpfile
