version: 2
root-markers:
  - .git/

tools:
  python-flake8: &python-flake8
    lint-command: 'flake8 --ignore=E501,F401,F821,F841,W503 --stdin-display-name ${INPUT} -'
    lint-stdin: true

languages:
  python:
    - <<: *python-flake8
